#A = (1, 4, 2, 5)
#print(type(A))
#print(*A)
first = 'from me'
new = 'hello world'.title()
print('{}' .format(new))
print(new .swapcase())
print(new .split())
print(' '.join(new))
print(new .index('W'))
print(new .count(new))
print('{} = {}' .format('anabel',0), '\n')
print('{} = {}' .format('jack',1), '\n')
print('{} = {}' .format('jacob',2), '\n')
print('{} = {}' .format('jalang',3), '\n')
print('{} = {}' .format('john',4), '\n')
print('{} = {}' .format('jonathan',5), '\n')
print('{} = {}' .format('tabita',6), '\n')
print('{} = {}' .format('winifred',7), '\n')
